package Enums;

public enum AttackID {
	//Small 16x32 attacks. Enums are order specific
	SMALL_FIRE_PROJECTILE, SMALL_BONE_PROJECTILE, SMALL_POISON_PROJECTILE,
	BONE_SWIPE,
	UNUSED_06,
	UNUSED_07,
	UNUSED_08,
	UNUSED_09,
	UNUSED_10,
	UNUSED_11,
	UNUSED_12,
	UNUSED_13,
	UNUSED_14,
	UNUSED_15,
	UNUSED_16,
	UNUSED_17,
	UNUSED_18,
	UNUSED_19,	
	
	//AOE attacks.
	SMALL,AOE_FIRE,
	

}
