package Enums;

public enum EffectTrigger {	
	ON_DEATH,
	ON_DEATH_BY_PHYSICAL_DMG,
	ON_DEATH_BY_ELEMENTAL_DMG,
	ON_DEATH_BY_MELEE_DMG,
	ON_DEATH_BY_RANGED_DMG,
	ON_DEATH_BY_MAGIC_DMG,
	ON_DEATH_BY_POISON_DMG,
	ON_DEATH_BY_BURN_DMG,
	ON_DEATH_BY_HEX_DMG,
	
	ON_RECIEVE_DMG,
	ON_RECIEVE_MELEE_DMG,
	ON_RECIEVE_RANGED_DMG,
	ON_RECIEVE_MAGIC_DMG,
	ON_RECIEVE_POISON_DMG,
	ON_RECIEVE_BURN_DMG,
	
	ON_RECIEVE_POISON,
	ON_RECIEVE_BURN,
	
	ON_GIVE_DMG,
	ON_GIVE_MELEE_DMG,
	ON_GIVE_RANGED_DMG,
	ON_GIVE_MAGIC_DMG,
	
	ON_MOVE,
	ON_SUMMON,
	ON_MINION_DEATH,
	ON_MINION_DAMAGE,
	ON_HEAL,
	ON_MINION_HEAL,
	
	EVERY_1_SEC,
	EVERY_2_SEC,
	EVERY_3_SEC,
	EVERY_4_SEC,
	EVERY_5_SEC;
	
	public String getText(){
		switch(this){
		case ON_DEATH:
			break;
		}
		
		return null;
	}
	

}
