package Enums;

public enum EffectTrigger {	
	ON_DEATH,
	ON_DEATH_BY_PHYSICAL_DMG,
	ON_DEATH_BY_ELEMENTAL_DMG,
	ON_DEATH_BY_MELEE_DMG,
	ON_DEATH_BY_RANGED_DMG,
	ON_DEATH_BY_MAGIC_DMG,
	ON_DEATH_BY_POISON_DMG,
	ON_DEATH_BY_BURN_DMG,
	ON_DEATH_BY_HEX_DMG,
	
	ON_RECIEVE_DMG,
//	ON_RECIEVE_PHYSICAL_DMG,
//	ON_RECIEVE_ELEMENTAL_DMG,
	ON_RECIEVE_MELEE_DMG,
	ON_RECIEVE_RANGED_DMG,
	ON_RECIEVE_MAGIC_DMG,
	ON_RECIEVE_POISON_DMG,
	ON_RECIEVE_BURN_DMG,
//	ON_RECIEVE_HEX_DMG,
	
	ON_RECIEVE_POISON,
	ON_RECIEVE_BURN,
//	ON_RECIEVE_HEX,
	
	ON_GIVE_DMG,
//	ON_GIVE_PHYSICAL_DMG,
//	ON_GIVE_ELEMENTAL_DMG,
	ON_GIVE_MELEE_DMG,
	ON_GIVE_RANGED_DMG,
	ON_GIVE_MAGIC_DMG,
	
	ON_MOVE,
	ON_SUMMON,
	ON_MINION_DEATH,
	ON_HEAL,
	ON_MINION_HEAL,
	
	EVERY
	

}
